-- Fix H-6: Remove generate_app_number trigger that silently overwrites
-- the frontend-generated application_number (TZ-SERVICE-YYYYMMDD-XXXX format).
-- The frontend generates the number and passes it in the INSERT; the trigger
-- was firing BEFORE INSERT and replacing it with APP-YYYYMMDD-XXXX, causing
-- a mismatch between what citizens see and what is stored in the database.

DROP TRIGGER IF EXISTS tr_generate_app_number ON public.applications;
DROP FUNCTION IF EXISTS generate_app_number();

-- Ensure the column has a NOT NULL constraint with a safe fallback
-- (frontend always provides this value, but guard against edge cases)
ALTER TABLE public.applications
    ALTER COLUMN application_number SET DEFAULT NULL;

COMMENT ON COLUMN public.applications.application_number IS
    'Generated by the frontend in format TZ-SERVICE-YYYYMMDD-XXXX (e.g. TZ-MKZ-20260601-1234). Must be unique.';
